# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4df32ba578c80e7b8ff0402ca51a27f5977493b5ab17baa6fde2c2531f1dc9d1743a4fbfbd78147fd7a384b4b00dca47f4b8897fbce8056be55ad196020f5f61

test:
  secret_key_base: 251311c7701ec28754935f60d808e118bbf8e2e67e647ebddfc3a8783d15d0bd99ffd70696e6df12660db8a42b760ac5156409a05150480bb3c86e59a607ee8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
